controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

presentation:
    resource: ../../src/Presentation/
    type: annotation
